name: Teste de Conexão com Servidor

on:
  workflow_dispatch:

jobs:
  ping-servidor:
    runs-on: ubuntu-latest
    steps:
      - name: Testar acesso HTTP ao servidor
        run: |
          curl -I http://179.124.139.117:443 || echo "Falhou"

      - name: Testar acesso à porta com netcat
        run: |
          nc -zv 179.124.139.117 443 || echo "Porta inacessível"
